# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4ecf70673dc5242fbe52688fef937e773bcbda06ba74807c9ea5921129cf21ab8e6c511270762e75ae83e8beb515db0f5e343bca01ebc3214e6abd4670be7f1

test:
  secret_key_base: 349419d61c6918691b6700781d68190f8aef41c3e1704e9c15a155340d4903605f6df2787887081aa2d9a11906d7f384b4a94049b86dc89f24ad74a72f85b559

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
